apiVersion: v1
kind: Service
metadata:
  name: road-crossing-service
spec:
  selector:
    app: road-crossing
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
